name: auto_shimmer_animate_example
description: Example app for the auto_shimmer_animate package.
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  auto_shimmer_animate:
    path: ..
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
