name: auto_shimmer_animate
description: A Flutter package that automatically converts existing widget trees into animated shimmer skeleton loading states.
version: 0.2.0
homepage: https://github.com/kartikhadiya09/auto_shimmer_animate
repository: https://github.com/kartikhadiya09/auto_shimmer_animate
issue_tracker: https://github.com/kartikhadiya09/auto_shimmer_animate/issues
license: MIT

topics:
  - shimmer
  - skeleton
  - loading
  - placeholder
  - animation

screenshots:
  - description: Default Auto Shimmer Animate skeleton loading demo.
    path: screenshots/default-example.gif
  - description: Auto Shimmer Animate custom color demo.
    path: screenshots/custom-color-example.gif
  - description: Auto Shimmer Animate aurora effect demo.
    path: screenshots/aurora-example.gif

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
